[template]
src = "prometheus.yml"
dest = "/etc/prometheus/confd-prometheus.yml"
keys = [
    "/path/to/your/prometheus/access_key",
    "/path/to/your/prometheus/secret_key",
    "/path/to/your/prometheus/barer_token"
]
