global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'Prometheus'
    static_configs:
    - targets: ['localhost:9090']
    basic_auth:
      username: admin
      password: {{getenv "DASHBOARD_PASSWORD"}}

  - job_name: EC2
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_private_ip]
        target_label: ip
    ec2_sd_configs:
      - region: us-east-1
        role_arn: {{getenv "EC2_ROLE_ARN"}}
        port: 9100

  - job_name: Application
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_private_ip]
        target_label: ip
    ec2_sd_configs:
      - region: us-east-1
        role_arn: {{getenv "EC2_ROLE_ARN"}}
        port: 80
    basic_auth:
      username: prometheus
      password: {{getenv "METRICS_PASSWORD"}}

  - job_name: ECS
    file_sd_configs:
      - files:
        - /etc/prometheus/ecs_file_sd.yml
        refresh_interval: 1m
    scrape_interval: 1m
    scrape_timeout: 30s

